name: run main.py

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:

      - name: checkout repo content
        uses: actions/checkout@v3 # checkout the repository content to github runner

      - name: setup python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11.1' 
          
      - name: install python packages
        run: |
          python -m pip install --upgrade pip
          pip install flake8 pytest
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      - name: execute py script # run main.py
        env:
          ServiceAccountKey: ${{ secrets.SERVICEACCOUNTKEY }}
        run: python Source/app.py
          
      - name: commit files
        run: |
          git config --local user.email "edison.phua2004@gmail.com"
          git config --local user.name "EdisonPhua"
          git add -A
          git diff-index --quiet HEAD || (git commit -a -m "updated logs" --allow-empty)
          
      - name: push changes
        uses: ad-m/github-push-action@v0.6.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: main 
