name: Print Secret

on: [push]

env:
  SERVICEACCOUNTKEY: ${{ secrets.SERVICEACCOUNTKEY }}

jobs:
  print_secret:
    runs-on: ubuntu-latest
    steps:
    - name: Print Secret
      run: |
        echo "The secret is: $MY_SECRET"
